export const CREATE_ADDRESS_REQ = 'CREATE_ADDRESS_REQ';
export const CREATE_ADDRESS_SUCCED = 'CREATE_ADDRESS_SUCCED';
export const CREATE_ADDRESS_FAILED = 'CREATE_ADDRESS_FAILED';
// get
export const GET_ADDRESS_REQ = 'GET_ADDRESS_REQ';
export const GET_ADDRESS_SUCCED = 'GET_ADDRESS_SUCCED';
export const GET_ADDRESS_FAILED = 'GET_ADDRESS_FAILED';