// GET ROW
export const GET_HOSTED_REQUEST = "GET_HOSTED_REQUEST";
export const GET_HOSTED_SUCCED = "GET_HOSTED_SUCCED";
export const GET_HOSTED_FAILED = "GET_HOSTED_FAILED";

// CREATE HOSTED
export const CRETAE_HOSTED_REQ = "CRETAE_HOSTED_REQ";
export const CRETAE_HOSTED_SUCCED = "CRETAE_HOSTED_SUCCED";
export const CRETAE_HOSTED_FAILED = "CRETAE_HOSTED_FAILED";

//UPDATE HOSTED
export const UPDATE_HOSTED_REQ = "UPDATE_HOSTED_REQ";
export const UPDATE_HOSTED_SUCCED = "UPDATE_HOSTED_SUCCED";
export const UPDATE_HOSTED_FAILED = "UPDATE_HOSTED_FAILED";

// DELETE HOSTED
export const DELETE_HOSTED_REQ = "DELETE_HOSTED_REQ";
export const DELETE_HOSTED_SUCCED = "DELETE_HOSTED_SUCCED";
export const DELETE_HOSTED_FAILED = "DELETE_HOSTED_FAILED";
