//get by pages
export const GET_HUSES_REQ = "GET_HUSES_REQ";
export const GET_HUSES_SUCCED = "GET_HUSES_SUCCED";
export const GET_HUSES_FAILED = "GET_HUSES_FAILED";
//get one
export const GET_ONE_HUSES_REQ = "GET_ONE_HUSES_REQ";
export const GET_ONE_HUSES_SUCCED = "GET_ONE_HUSES_SUCCED";
export const GET_ONE_HUSES_FAILED = "GET_ONE_HUSES_FAILED";
// get all
export const GET_ALL_HOUSES_REQ = "GET_ALL_HOUSES_REQ";
export const GET_ALL_HOUSES_SUCCED = "GET_ALL_HOUSES_SUCCED";
export const GET_ALL_HOUSES_FAILED = "GET_ALL_HOUSES_FAILED";
//DELETE
export const DElETE_HUSES_REQUEST = "DElETE_HUSES_REQUEST";
export const DELETE_HUSES_SUCCED = "DELETE_HUSES_SUCCED";
export const DELETE_HUSES_FAILED = "DELETE_HUSES_FAILED";
//create
export const ADD_HOUSES_REQ = "ADD_HOUSES_REQ";
export const ADD_HOUSES_SUCCED = "ADD_HOUSES_SUCCED";
export const ADD_HOUSES_FAILED = "ADD_HOUSES_FAILED";
//update
export const UPDATE_HOUSES_REQ = "UPDATE_HOUSES_REQ";
export const UPDATE_HOUSES_SUCCED = "UPDATE_HOUSES_SUCCED";
export const UPDATE_HOUSES_FAILED = "UPDATE_HOUSES_FAILED";
