export const GET_LINES_REQ = "GET_LINES_REQ";
export const GET_LINES_SUCCED = "GET_LINES_SUCCED";
export const GET_LINES_FAILED = "GET_LINES_FAILED";
//delete
export const DELETE_LINES_REQ = "DELETE_LINES_REQ";
export const DELETE_LINES_SUCCED = "DELETE_LINES_SUCCED";
export const DELETE_LINES_FAILED = "DELETE_LINES_FAILED";
// get by order
export const GET_LINES_BY_ORDER_REQ = "GET_LINES_BY_ORDER_REQ";
export const GET_LINES_BY_ORDER_SUCCED = "GET_LINES_BY_ORDER_SUCCED";
export const GET_LINES_BY_ORDER_FAILED = "GET_LINES_BY_ORDER_FAILED";
