export const CREATE_ORDER_REQ = "CREATE_ORDER_REQ";
export const CREATE_ORDER_SUCCED = "CREATE_ORDER_SUCCED";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
//get
export const GET_ORDER_REQ = "GET_ORDER_REQ";
export const GET_ORDER_SUCCED = "GET_ORDER_SUCCED";
export const GET_ORDER_FAILED = "GET_ORDER_FAILED";
//cencel order
export const CANCEL_ORDER_REQ = "CANCEL_ORDER_REQ";
export const CANCEL_ORDER_SUCCED = "CANCEL_ORDER_SUCCED";
export const CANCEL_ORDER_FAILED = "CANCEL_ORDER_FAILED";
// get order cancelled
export const GET_ORDER_CANCEL_REQ = "GET_ORDER_CANCEL_REQ";
export const GET_ORDER_CANCEL_SUCCED = "GET_ORDER_CANCEL_SUCCED";
export const GET_ORDER_CANCEL_FAILED = "GET_ORDER_CANCEL_FAILED";
